---
title: "R Notebook"
output: html_notebook
---


```{r, echo = F, warning=F, message=F}
########################################################################
### Load packages and data ---------------------------------------------

## Packages
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)
library(readxl)
library(broom)
library(readr)
library(corrplot)
library(knitr)
library(stargazer)

## Data files
# Fishery and aquaculture production data
phils_prod <- read.csv(file = '../../Google Drive/Project Data/phils-data/phils-prod-80-12/phils_prov_prod_80to12_1.csv', header = F, na.strings = c('.','..'), stringsAsFactors = F) %>%
  bind_rows(read.csv(file = '../../Google Drive/Project Data/phils-data/phils-prod-80-12/phils_prov_prod_80to12_2.csv', header = F, na.strings = c('.','..'), stringsAsFactors = F))

colnames(phils_prod) <- c('province_name','sector', c(1980:2012))

# Fishery and aquaculture value data
phils_val <- read.csv(file = '../../Google Drive/Project Data/phils-data/phils-prod-80-12/phils_prov_10to14_value_1.csv', header = F, na.strings = c('.','..'), stringsAsFactors = F) %>%
  bind_rows(read.csv(file = '../../Google Drive/Project Data/phils-data/phils-prod-80-12/phils_prov_10to14_value_2.csv', header = F, na.strings = c('.','..'), stringsAsFactors = F))

colnames(phils_val) <- c('province_name','sector', c(1980:2014))

# phils aquaculture data 1996 to 2014
phils_aqua <- read.csv(file = '../../Google Drive/Project Data/phils-data/phils_aqua_processed.csv', stringsAsFactors = F)

# Region socioeconomic data
region_data <- tbl_df(read.csv(file = '../../Google Drive/Project Data/phils-data/phils_fisheries_regions.csv', stringsAsFactors = F))

colnames(region_data) <- tolower(colnames(region_data))
```


```{r, echo=F, message=F, warning=F}
## Process data into single regression data file
phils_prod <- phils_prod %>%
  gather(year, harvest, 3:35) %>%
  mutate(year = as.numeric(year)) %>%
  spread(sector, harvest)

phils_val <- phils_val %>%
  select(-`2013`, -`2014`) %>%
  gather(year, value, 3:35) %>%
  mutate(year = as.numeric(year)) %>%
  spread(sector, value)

phils <- left_join(phils_prod, phils_val, by = c("province_name", 'year'))

phils$province_name <- toupper(gsub(phils$province_name, pattern = '....', replacement = '', fixed = T))

phils <- phils %>%
  rename(muni_marine_catch = `....Marine Municipal Fisheries.x`,
         aqua_harvest      = `..Aquaculture.x`,
         comm_catch        = `..Commercial Fisheries.x`,
         muni_catch        = `..Municipal Fisheries.x`,
         muni_marine_value = `....Marine Municipal Fisheries.y`,
         aqua_value      = `..Aquaculture.y`,
         comm_value        = `..Commercial Fisheries.y`,
         muni_value        = `..Municipal Fisheries.y`) %>%
  group_by(province_name, year) %>%
  mutate(all_catch  = sum(muni_marine_catch + comm_catch, na.rm = T),
         all_value  = sum(muni_marine_value + comm_value, na.rm = T),
         muni_price = muni_marine_value / muni_marine_catch,
         aqua_price = aqua_value / aqua_harvest,
         comm_price = comm_value / comm_catch,
         all_price  = all_value / all_catch)

```

```{r, echo=F, message=F, warning=F}

# aggregate all fishery and aquaculture data by region
phils_aqua_df <- phils_aqua %>%
  rename(aqua_harvest  = harvest,
         aqua_price    = price,
         aqua_value_us = value_us,
         farm_type     = archetype) %>%
  group_by(province_name, farm_type, year) %>%
  summarize(aqua_harvest  = sum(aqua_harvest, na.rm = T),
            aqua_value_us = sum(aqua_value_us, na.rm = T),
            aqua_price    = sum(aqua_value_us, na.rm = T) / sum(aqua_harvest, na.rm = T)) %>%
  ungroup()

## Assign variables by culture type 
farm_culture <- data_frame(farm_type    = unique(phils_aqua_df$farm_type),
                           culture_type = c('Marine', 'Marine', 'Seaweed', 'Freshwater', 'Marine', 'Freshwater', 'Freshwater',
                                            'Mussel', 'Oyster', 'Freshwater', 'Freshwater', 'Marine', 'Marine'))
# Spread culture types out 
aqua_harvest <- phils_aqua_df %>%
  left_join(farm_culture) %>%
  select(province_name, culture_type, year, aqua_harvest) %>%
  group_by(province_name, culture_type, year) %>%
  summarize(aqua_harvest = sum(aqua_harvest, na.rm = T)) %>%
  spread(culture_type, aqua_harvest) 

colnames(aqua_harvest) <- c('province_name','year','freshwater_harvest','marine_harvest','mussel_harvest','oyster_harvest','seaweed_harvest')

aqua_price <- phils_aqua_df %>%
  left_join(farm_culture) %>%
  select(province_name, culture_type, year, aqua_value_us, aqua_harvest) %>%
  group_by(province_name, culture_type, year) %>%
  summarize(aqua_price = sum(aqua_value_us, na.rm = T) / sum(aqua_harvest, na.rm = T)) %>%
  spread(culture_type, aqua_price) 

colnames(aqua_price) <- c('province_name','year','freshwater_price','marine_price','mussel_price','oyster_price','seaweed_price')

phils_aqua_df <- aqua_harvest %>%
  left_join(aqua_price) %>%
  select(province_name, year, marine_harvest, marine_price)
  
```


```{r, echo=F, warning=F, message=F}
########################################################################
### Prepare socioeconomic data for inclusion in regression 

# Aggregate by region 
reg_1 <- region_data %>%
  tbl_df() %>%
  select(-x, -region_psgc, -province_psgc, -municipal_psgc, -psgc, -component.lgu, -income_class) %>%
  separate(income.class, into = c('income_class','drop'), sep = '[[:lower:]]') %>%
  mutate(income_class = as.numeric(income_class)) %>%
  group_by(province_name) %>%
  summarize(length_coast     = sum(length_of_coastline_km, na.rm = T),
            no_barangays     = sum(no_of_barangays, na.rm = T),
            area_muni_waters = sum(area_of_municipal_waters_ha, na.rm = T),
            income_class     = mean(income_class, na.rm = T),
            mangroves        = sum(mangroves, na.rm = T),
            coral            = sum(coralreefs, na.rm = T)) %>%

  ungroup()

# Extract and spread population data into single variable
reg_pop <- region_data %>%
  select(province_name, population_1980, population_1990, population_2000, population_2010) %>%
  gather(pop_var, population, 2:5) %>%
  group_by(province_name, pop_var) %>%
  summarize(area_population = sum(population, na.rm = T)) %>%
  separate(pop_var, into = c('variable', 'years'), sep = '_') %>%
  mutate(years = as.numeric(years)) %>%
  complete(years = 1980:2013) %>%
  rename(year = years) %>%
  ungroup()

regs <- unique(reg_pop$province_name) # unique regions

# Fill in missing years for population
for(a in 1:length(regs)) {
  reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year < 1990] <- reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year == 1980]
  reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year > 1990 & reg_pop$year < 2000 ] <- reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year == 1990]
  reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year > 2000 & reg_pop$year < 2010 ] <- reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year == 2000]
  reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year > 2010 ] <- reg_pop$area_population[reg_pop$province_name == regs[a] & reg_pop$year == 2010]
}

phils <- phils %>%
  left_join(reg_1) %>%
  left_join(reg_pop) 
```


```{r, echo=F, warning=F, message=F}
# Subset to only municipalities with non-zero area of waters
phils_reg <- phils %>%
  ungroup() %>%
  filter(area_muni_waters > 0) %>%
  filter(!(province_name == 'EASTERN SAMAR' & year == 1995))

# Model 1 - regressing municipal catch
m1 <- glm(log(muni_marine_catch) ~ aqua_harvest, family = gaussian(link = 'log'), data = phils_reg)
m1a <- glm(log(muni_marine_catch) ~ aqua_price, family = gaussian(link = 'log'), data = phils_reg)

# Model 2 - regressing municipal catch
m2_vars <- c('province_name','aqua_harvest','aqua_value', 'all_value')  
fmla_2 <- as.formula(paste("log(muni_marine_catch) ~ ", paste( m2_vars, collapse= "+"))) 
m2 <- glm(fmla_2, family = gaussian(link = 'log'), data = phils_reg)

# Model 3 - regressing commercial catch
m3_vars <- c('province_name','aqua_harvest','aqua_value', 'all_value')  
fmla_3 <- as.formula(paste("log(comm_catch) ~ ", paste( m3_vars, collapse= "+"))) 
m3 <- glm(fmla_3, family = gaussian(link = 'log'), data = phils_reg)

# summary(m1)
# summary(m2)
# summary(m3)

cor_df <- phils_reg %>%
  select(all_catch, aqua_harvest, aqua_price, all_price, area_population) %>%
  mutate(all_catch = log(all_catch))

test <- cor(cor_df, use = 'complete.obs')

corrplot(test, addCoef.col = T)
```

### Results

```{r, echo=F, results='asis', warning=F}
tbl_1 <- stargazer(m1, m1a, type = 'html')

```

```{r, echo=F, message=F, warning=F, eval=F}

test <- phils_reg %>%
  left_join(phils_aqua_df) %>%
  filter(year > 1995)

# Model 2 - regressing municipal catch
m2_vars <- c('province_name','marine_harvest','all_price','area_population')  
fmla_2 <- as.formula(paste("log(muni_marine_catch) ~ ", paste( m2_vars, collapse= "+"))) 
m2 <- glm(fmla_2, family = gaussian(link = 'log'), data = test)

summary(m2)

s```
