---
title: Interactions and management for the future of marine aquaculture and capture
  fisheries
csl: apa.csl
output:
  word_document:
    reference_docx: "../../My-code/word_rmarkdown_styles.docx"
bibliography: aqua_interactions_biblio.bib
---

Tyler Clavelle^1\*^, Sarah E. Lester^2^, Rebecca Gentry^1^, Halley E. Froehlich^3^
  
^1^ Bren School of Environmental Science and Management, University of California, Santa Barbara, Santa Barbara, CA 93106, USA
  
^2^ Department of Geography, Florida State University, Tallahassee, FL 32306-2190, USA
  
^3^ National Center for Ecological Analysis and Synthesis, University of California, 735 State Street, Suite 300, Santa Barbara, CA 93101, USA
  
^\*^ Corresponding author: Tyler Clavelle (tyler_clavelle@ucsb.edu)
 

# Abstract
Aquaculture surpassed wild fisheries as the largest supplier of fish for human consumption in 2014 and is expected to supply the majority of seafood for future increases in demand. Marine and coastal aquaculture, collectively referred to as mariculture, currently represents just 36% of aquaculture production but is poised to expand in the decades ahead. One of the most commonly cited concerns regarding this likely expansion is ecological and socioeconomic interactions with wild-capture fisheries. While attention has largely been drawn to high profile negative externalities from fed finfish and crustacean mariculture, not all marine-based practices are equivalent. Empirical evidence for the different interactions between mariculture and wild fisheries is often sparse. While negative consequences can arise, positive synergies can also occur. By considering mariculture development in the context of fisheries interactions, we suggest that it is possible to minimize conflicts and maximize positive connections between the two sectors. We provide the first comprehensive synthesis of the interactions between mariculture and wild fisheries, characterizing the types of interactions, evaluating available empirical evidence, and identifying where management (sector-specific and cooperative) can play an important role. We highlight potential effects of mariculture on the efficiency, sustainability, and equity of seafood production and identify remaining knowledge gaps.
Keywords: disease, fish farm, fishmeal, fishing, mariculture, seafood
 
# Introduction
Aquaculture recently surpassed capture fisheries as the primary source of seafood, contributing 73.8 million metric tons (MT) of seafood for direct human consumption in 2014 (50.4% of the total; Figure 1). Indeed, aquaculture is the world’s fastest growing food sector, and with only modest gains from capture fisheries expected, aquaculture will play a key role in providing for projected growth in seafood demand (FAO, 2016; Kobayashi et al., 2015). Marine species are being farmed at a rapid pace, increasing viable culture areas, diversifying product offerings, and expanding the range of market prices for consumers (Duarte, Marbá, & Holmer, 2007). Mariculture (i.e., farming of marine species in the ocean, in saltwater coastal ponds, or in saltwater tanks on land) can be among the most efficient sources of animal protein (Clark & Tilman, 2017; Hilborn et al., 2018, Poore & Nemecek, 2018). Also, in the case of offshore aquaculture, ocean space available for mariculture production is estimated to be considerably larger than is needed to feed the world, which stands in contrast to scarce land and freshwater resources required for food production on land (Duarte et al., 2009; Gentry et al., 2017a). Mariculture is dominated by unfed production of aquatic plants and filter feeding bivalves and molluscs, followed by marine finfish (primarily Salmonids), and shrimps and prawns (Figure 1). Nonetheless, when aquatic plants are excluded, mariculture’s current contribution to seafood supply is smaller than both its inland (freshwater) counterpart and the capture fisheries sector (Figure 1), providing only 36% (26.7 million MT) of global aquaculture production and 18.25% of all seafood for human consumption in 2014 (FAO, 2016).

Primary concerns regarding future growth in marine farming include the uncertain ecological and socioeconomic implications for wild fisheries. And yet, existing analyses examining the future of seafood production largely ignore interactions between capture fisheries and mariculture (exceptions include Merino et al. (2012) and Watson et al. (2015)). Several influential studies have warned that, without adopting more ecologically sound management practices, an expanded aquaculture industry could make the world’s food supply less resilient by posing a threat to ocean fisheries (Cao et al., 2015; Naylor et al., 2000; Naylor, Williams, & Strong, 2001; Smith et al., 2010; Troell et al., 2014). Indeed, fishers often strongly oppose mariculture development (Tiller, Gentry, & Richards, 2013) and the effects on wild fisheries has become a common source of public concern regarding the sector’s expansion (Froehlich, Gentry, Rust, Grimm, & Halpern, 2017).

As a result of heterogeneity in both mariculture and wild fisheries, the two sectors interact in a variety of ways that can be detrimental, neutral or beneficial. These interactions can be influenced by a range of factors, such as the similarity of the farmed and wild species; the farming methods (e.g. pond, cage, raft, line, etc.), scale, and intensity level; farm location (e.g. coastal, offshore); the types of fisheries involved; and the institutions and regulations governing fisheries and mariculture. Here we organize interactions into two categories: ecological and socioeconomic (Table 1). Ecological interactions include direct (e.g. wild fish as feed, disease) and indirect (e.g. water quality, habitat modification) ways that mariculture farms affect wild populations targeted by capture fisheries. Extensive reviews exist for numerous important ecological interactions, including disease and parasite impacts (Costello, 2006; Johansen et al., 2011; Lafferty et al., 2015; Torrissen et al., 2013), water quality and benthic effects (Kalantzi & Karakassis, 2006; Price, Black, Hargrave, & Jr, 2015), and genetic implications of escaped farm fish and hatchery practices (Araki & Schmid, 2010; Glover et al., 2012; Karlsson, Diserud, Fiske, & Hindar, 2016). Socioeconomic interactions are those that affect fishers and fisheries in other ways, such as exclusion from traditional fishing grounds or increased demand for seafood. Based on our survey of the literature and a more systematic assessment of the breadth of topics covered in the aquaculture literature (Natale et al., 2012), it appears these interactions have received considerably less scholarly attention.    

This work reviews and synthesizes the type, scale, and direction of potential ecological and socioeconomic interactions between capture fisheries and mariculture to facilitate their consideration in future management decisions and research endeavors. For each type of potential interaction, we review the current scientific understanding within the context of different farming and fishing practices. We then evaluate strategies for managing the interactions between these two food-producing sectors and consider how current fisheries management approaches can be utilized to promote positive ecological and economic outcomes.

# Ecological Interactions
Capture fisheries and mariculture are linked directly and indirectly through numerous ecological interactions (Figure 2). These connections occur primarily at local and regional levels and warrant considerable attention from fishery managers due to the generally negative potential effects on wild populations. Importantly, the intensity of farming practices and the scale, both of mariculture farms and adjacent capture fisheries, are key modifiers of nearly all ecological interactions. 

## Habitat modification
Marine habitats are directly affected by mariculture farms via land conversion or the addition of artificial structures (e.g. anchors, moorings), and indirectly through nutrient loading, shading, and changes in hydrodynamics. In all cases, mariculture has the potential to influence the distribution and abundance of marine species in an area, with relevance for fisheries management.

### Habitat conversion
Mariculture’s degradation and conversion of coastal habitats is well documented (Naylor et al., 1998). Shrimp mariculture is widely credited as the primary driver of mangrove deforestation in the 1980s and 1990s and remains a concern across Southeast Asia, Central America, and northern South America (Polidoro et al., 2010). Habitat conversion rates have slowed considerably in recent decades as awareness of the problem has grown; the percentage of mariculture converted habitat in Southeast Asia declined by 50% since the 1980s-1990s (Hishamunda, Ridler, Bueno, & Yap, 2009). Unfortunately, mariculture remains the top replacement use (30%) for mangrove deforestation across Southeast Asia (Richards & Friess, 2016). 

Impacts of mariculture on seagrass are highly variable and depend on a large number of factors, including depth, hydrodynamics, grow out and harvesting approach, degree of shading, and overgrazing by herbivores (Ruiz, Pérez, & Romero, 2001; Ferriss et al 2019). Seagrass loss and degradation has been observed below finfish farms in the Mediterranean (Marbà, Santiago, Díaz-Almela, Álvarez, & Duarte, 2006), but the effect of shellfish farming on seagrass is less clear. For eelgrass (Zostera marina, Zosteraceae), studies have shown clear negative impacts from shading (Skinner, Courtenay, McKindsey, Carver, & Mallet, 2014) and space competition (Ferris et al 2019), as well as resiliency (Dumbauld & McCoy, 2015). Better and more geographically representative empirical estimates of mariculture’s effect on seagrass, and implications for wild fisheries dependent on these habitats, are particularly critical given the accelerating loss of seagrasses across the globe (Waycott et al., 2009). 

Mariculture installations can directly impact coral reefs by using them as anchors, decreasing access to sunlight, and, in the case of fed mariculture, causing nutrient enrichment (Fabricius, 2005; Loya, Lubinevsky, Rosenfeld, & Kramarsky-Winter, 2004). Reefs are often found in areas with the same environmental conditions needed by mariculture - clear nutrient poor waters with protection from strong winds and waves. More than 50% of sea cage farms in Southeast Asia were found to exist less than one kilometer from a reef (Hedberg, Kautsky, Hellström, & Tedengren, 2015), but the specific ecological consequences of such proximity remain unclear.

The potential of mariculture to degrade sensitive habitats may disproportionately affect coastal fisheries, particularly in developing regions that are often poorly managed. The general importance of coastal habitats as nursery grounds for fished species is well documented (Mumby, Edwards, & Lindeman, 2004; Sundblad, Bergström, Sandström, & Eklöv, 2014). However, empirically linking habitat loss to changes in abundance of fished species and quantifying resulting changes in fishing yields can be difficult. A large body of research has examined this relationship with respect to mangroves and coastal fisheries, showing that estimates can vary with region and species by orders of magnitude (Aburto-Oropeza et al., 2008; Barbier et al., 2010; Vázquez-González et al., 2015). Importantly, ecosystem services provided by coastal habitats are rarely linear, suggesting that stark thresholds may exist in their relationship with fishery value (Barbier et al., 2008). It is possible that, in some areas, avoiding habitat loss from mariculture development should be a top management objective. Globally, other development forms and stressors are currently larger threats to coastal habitats and species (Halpern et al., 2008; McCauley et al., 2015), but proper mariculture siting will be critical as the industry expands.

### Artificial habitat and de facto protection
Mariculture farms can influence the abundance, diet, and/or residence time of wild fish in an area, with confounding economic and conservation implications (Arechavala-Lopez et al., 2011; Bacher, Gordoa, & Sagué, 2015). The artificial structure and potential food source provided by farms can act as fish aggregating devices (FADs) that attract (or repel) a wide variety of wild species (Bortone, Brandini, Fabi, & Otake, 2011; Dempster, Sanchez-Jerez, Bayle-Sempere, Giménez-Casalduero, & Valle, 2002; Dempster et al., 2009; Hehre & Meeuwig, 2016; Callier et al 2017). The distribution of species associated with mariculture farms varies over spatial and temporal scales and mechanisms by which species are attracted or repelled have a variety of direct and indirect effects at the individual and population levels (Callier et al. 2017). Data on these interactions are sparse, impeding our ability to predict downstream effects with any great certainty. Hypothetically, the FAD effect could yield economic benefits for a fishery by allowing for steady catches with lower effort, or could lead to overexploitation if there are not regulations or other mechanisms to ensure sustainable catch levels. Farms may also serve as de facto marine protected areas (MPAs) if fishing is excluded from the area, and adjacent fisheries could potentially benefit via adult spillover (Halpern, Lester & Kellner, 2009) and/or larval export, as have been demonstrated for some MPAs. The possibility of mariculture farms providing spillover or export benefits likely depends on the location of farms, the size of farms relative to the movement rate (or dispersal distance) of the fished species, and whether the farms degrade or enhance the species’ habitat (Mikkelsen, 2006). 

Evidence on the relative strength of FAD and MPA effects of mariculture farms is mixed and more research is needed. Bacher & Gordoa (2016) monitored commercial and recreational fishing near a single fish farm in the Mediterranean and found fishers spent 9% of fishing days near farms but experienced no significant difference in catch rates when the boat was near the farm or farther away. The authors note that farm workers harvested more than four metric tons of wild fish within the farm annually, arguing that the farms act more like “ecological traps” that attract fish away from surrounding waters, diminishing their populations. Conversely, Machias et al. (2006) looked at time series of landings by local fishing fleets in Greece and found that development of mariculture in a region either had no effect or a positive effect on landings. Similarly, Arechavala-Lopez et al. (2011) studied landings of the commercial and artisanal fisheries operating in proximity to three fish farms off southeastern Spain. Using dietary analysis, the authors showed that the artisanal fleet caught fish that had previously aggregated near the fish farms, and thus the fishery benefitted from a “biomass export” from fish farms at a local scale. The attraction of larger predatory fish and mammals to mariculture farms has been documented and may increase predation on target fisheries species (Dempster et al., 2002). Additionally, because farms are often sited over soft bottom habitats, farm structures may displace species that associate with soft bottom while attracting those that prefer hard substrate (McKindsey, Archambault, Callier, & Olivier, 2011). Overall, empirical evidence of the bioeconomic effects of mariculture’s ability to attract and protect fish is clearly needed. Until robust estimates exist, it will remain unclear when, how, and what types of farms result in net gains or losses for fisheries and populations of wild harvest species.

### Water quality
Poor water quality, as a result of altered nutrient cycling, is a well-established potential effect of fed open ocean and coastal mariculture, with largely negative impacts on both farmed and wild species. Organic enrichment resulting from the deposition of excess feed and fecal matter from fed mariculture can alter abundance, biomass, and diversity of benthic faunal communities (Wu, 1995). In the case of open-ocean fish farms, benthic impacts are generally localized to the immediate vicinity under the farm (< 1 km), but vary considerably with farm depth and current speeds (Kalantzi & Karakassis, 2006). Similarly, nutrient enrichment of the water column is generally not detectable beyond 100 meters of a farm and there is little evidence of a direct link between open ocean fish farms and harmful algal blooms (Price et al. 2015). Although good management and modern operating conditions can largely eliminate the impacts of individual fish farms on water quality, questions remain about the additive impacts of multiple farms (Price et al., 2015). 
Saltwater ponds and tanks can also influence water quality through the discharge of effluent into the coastal environment (Yang et al., 2017; Piedrahita, 2003; Primavera, 2006). Water exchange rates and subsequent risks to coastal water quality generally increase with the intensity of farming practices, as intensive shrimp and fish ponds rely on water exchange to mitigate the eutrophicating effects of feed addition and prevent accumulation of toxic metabolites (Hopkins et al., 1993). Additionally, sediments in coastal ponds are the main sink for organic matter and nutrients, and thus complete drainage of intensive systems between production cycles results in rapid discharges of highly concentrated effluent (Wu et al., 2014). Pollution from these systems may be particularly detrimental to capture fisheries because effluents are often discharged into rivers and enter coastal water bodies through estuaries, which are nursery areas for many commercially important species (Páez-Osuna et al., 1998; Yang et al. 2017). However, shrimp aquaculture is trending towards low salinity, non-coastal production that may make water quality impacts from this growing sector less relevant to marine capture fisheries over time (Roy et al., 2010). 

Poor water quality is a major factor in the outbreak of marine diseases in mariculture, which have long been one of the largest causes of economic losses for the sector and can endanger wild populations targeted by capture fisheries (Johansen et al., 2011; Lafferty et al., 2015; Meyer, 1991). Although added nutrients can degrade benthic habitats and water quality, it can actually increase fishery landings and biodiversity in some cases, much like fertilizer effects in agricultural settings (Breitburg et al., 2009; Pitta et al., 2009). Machias et al. (2006) hypothesized that the positive impact of mariculture on fishery landings that they observed in Greece may be due to the additional source of food and nutrients to an oligotrophic (nutrient poor) environment, increasing overall productivity. 

Where water quality is poor, unfed species such as shellfish and seaweeds can help reduce coastal eutrophication through filter feeding and nutrient uptake (Gren, Lindahl, & Lindqvist, 2009). While unfed mariculture is generally lauded for its win-win benefits of seafood production and water filtration (Shumway et al. 2003; Rose et al. 2014), risks do exist (Gallardi, 2014), particularly from large-scale, high-intensity systems (Liu & Su, 2017). Hypothetically, filter feeders could reduce recruitment of fished species through high rates of larval consumption (Gibbs, 2004), a potential negative impact that merits further research as shellfish mariculture expands and moves further offshore. For example, incorporating larval dispersal models into the spatial planning process could help minimize adverse effects. Similarly, it is well established that filter feeding by bivalves alters and may even control phytoplankton biomass in shallow waters (Asmus and Asmus, 1991; Alpine and Cloern 1992; Gallardi, 2014). The degree to which feeding by farmed bivalves inhibits wild suspension feeders (including commercially targeted species), and how this effect scales with farm size, is a critical remaining knowledge gap. Lastly, although unfed mariculture generally does not rely on exogenous feed inputs, it does alter the natural cycling of nutrients. At large scales, this can increase sedimentation, weaken the flushing capability of bays and coastal areas, and potentially induce eutrophication or algal blooms that harm wild stocks (Shi et al. 2011; Bouwman et al. 2013). Thus, while unfed mariculture generally has a positive effect on water quality, there is evidence that ‘too much of a good thing’ is possible. 

### Wild fish inputs
Wild fish are used as feed inputs and as juveniles to stock mariculture farms, and this reliance of aquaculture on wild fish has long been a top concern of scientists and conservationists (Duarte et al., 2009; Naylor et al., 2000, 2009). In this context, mariculture can be classified into several categories that are critical for understanding the types and scale of impacts: fed versus unfed and capture-based versus hatchery-based. The use of wild fish is a key issue that requires both managing fisheries sustainably and fostering a regulatory environment for mariculture that supports continued innovation.

#### Feed
The share of fed species in total aquaculture production has been steadily increasing and now accounts for the majority (69.5%) of ‘food fish’ production from aquaculture (FAO, 2018). Production of fed species depends about equally on farm-based (local) and commercial (compound) feeds containing high concentrations of proteins and lipids traditionally sourced from fish meal and oil rendered from wild caught forage fish, such as herring, sardines, and menhaden (Tacon & Metian, 2008, 2015; Tacon, Hasan, & Metian, 2011). However, high costs resulting from the limited supply of forage fish have led many producers to reduce the percent of wild forage fish inputs and replace them with less expensive crop-based ingredients, including soy, wheat, and rapeseed (Troell; Tacon & Metian, 2015; Froehlich et al. 2018). Nonetheless, the use of wild fish for feed by the aquaculture sector is increasing as a result of overall growth, intensification of farming practices, and from the rising share of fed, higher trophic level species in total production (Tacon & Metian, 2008, 2009, 2015; Tacon, Hasan, & Metian, 2011). Given current trends in aquaculture and demand for seafood and terrestrial meat, estimates suggest the ecological limits of forage fish could be reached as soon as 2037, and sooner if precautionary measures further limit access to the wild resource (e.g., Atlantic herring, Clupea harengus, Clupdeidae) (Froehlich et al., 2018).

Forage fish play a key role in marine ecosystems by sustaining numerous higher tropic level species, many of which are commercially targeted (Alder, Campbell, Karpouzi, Kaschner, & Pauly, 2008; Essington et al., 2015; Smith et al., 2011). In fact, it has been estimated that fisheries supported by forage fish are actually more than twice as valuable as forage fisheries themselves, providing a strong economic argument for conservation (Pikitch et al., 2014). Much of the literature warns against aquaculture’s reliance on forage fish, citing the fully exploited, overexploited, or recovering status of many forage fisheries (Naylor et al., 2000), though now the current global amount being extracted appears below maximum sustainable levels (Froehlich et al., 2018; Hilborn & Costello, 2018). Yet, the sustainability of such practices remains divergent in the literature (Natale, Hofherr, Fiore, & Virtanen, 2013). Use of fishmeal and oil have a long history of use in the feed industry, starting with the agricultural sector (Alder et al., 2008). Notably, global forage fish landings for meal and oil have remained around 20-30 MMT since the mid-1980s, before aquaculture became the dominant user group (Alder et al., 2008; Kobayashi et al., 2015). Additionally, the proportion of world fisheries production used in aquaculture feeds is declining, despite steady growth in aquaculture production (FAO, 2016; Tacon & Metian, 2008). As a result, aquaculture has not necessarily changed the relative harvest pressure on forage fish stocks, but rather the economic value and portfolio of the resource.

For its part, the mariculture industry is making impressive gains in improving feed conversion ratios, reducing the inclusion of fishmeal in feed (as mentioned above), and developing substitutes (FAO, 2016; Klinger & Naylor, 2012; Naylor et al., 2009). The economic pressure from rising costs of fishmeal and fish oil is driving innovation by the mariculture sector, generating both economic opportunities and new risks for capture fisheries. An increasing share of fishmeal - some estimates as high as 25-35% - is being produced from fishery by-products, which were often previously discarded, adding value to many fisheries (FAO, 2016). An emerging concern is the depletion of low value and “trash” fisheries for direct feeding or use in lower quality farm-made feed (Cao et al., 2015). Because these fisheries are, by definition, relatively low value, they are generally not closely managed and their status is largely unknown. China, the world’s largest importer of fishmeal, reportedly uses an estimated 3 million MT of trash fish each year for direct feeding in mariculture (Funge-Smith, Fao, Lindebo, Staples, & Fao, 2005). This issue can also be observed by the increased diversity of fish used for purposes other than direct human consumption and the declining prominence of the formerly top ten taxa used for reduction to meal and oil (Cashion, Le Manach, Zeller, & Pauly, 2017). In contrast, a considerable portion of mariculture production (55%) comes from unfed shellfish and bivalve species that do not require exogenous wild fish inputs and are thus a very efficient source of animal protein. 

#### Seed
All mariculture activities require “seeding” the farm with juvenile fish (fingerlings, fry, seedlings), shellfish (spat), or algae. Capture-based mariculture depends on wild-caught juveniles for “seed”, which are then raised and fattened in captivity (Ottolenghi, Silvestri, Giordano, Lovatelli, & New, 2004). This practice, sometimes referred to as “ranching”, is widespread and an important source of production for many species, including tuna, shrimp, lobster, grouper, and eels (Lorenzen, Leber, & Blankenship, 2010). However, no current estimates of the extent of capture-based mariculture exist. Due to its direct link to wild populations, capture-based mariculture could lead to overfishing, with the severity of impacts on wild populations depending on the life stage, method of capture, and whether the wild population is recruitment limited (Ottolenghi et al., 2004). In the most extreme case, 99% of the bluefin tuna (Thunnus thynnus, Scombridae) catch in the Mediterranean Sea is sold to ranching operations, which either “fatten” recently mature fish for 3-7 months, or “farm” juvenile fish for up to two years until reaching market size (Metian, Pouil, Boustany, & Troell, 2014). Unfortunately, capture-based mariculture interferes in stock assessments by obscuring the size and age of harvested individuals, which has received little interest in the scientific literature (Ottolenghi et al., 2004). Of course, not all capture-based mariculture will have negative impacts on wild populations; for example, New Zealand’s greenshell mussel (Perna canaliculus, Mytilidae) industry obtains a large portion of its spat from kelp that has washed ashore, mussels that would otherwise suffer natural mortality (Hickman, 1976).

In contrast, hatchery-based mariculture obtains seedstock from hatcheries that breed domesticated fish species whose entire life cycle is closed in captivity. While there is debate around just how many species have been fully domesticated, the number is rising and is believed to be over 50% of species (freshwater and marine) listed in FAO’s aquaculture production statistics (Duarte et al., 2007; Teletchea & Fontaine, 2014). In its most developed form, hatchery-based mariculture employs selective breeding programs that focus on specific goals, such as growth rate, fillet yield, and flesh quality (Teletchea & Fontaine, 2014). Thus, although hatchery-based mariculture does not rely on sourcing juveniles from wild populations, escapes from hatchery-based mariculture farms pose a larger genetic threat to wild populations than escapes from capture-based farms due to their altered and less diverse gene pool.   

Hatcheries are also used to affect capture fishery harvests through stock enhancement, whereby wild populations are seeded with captive bred juveniles (Lorenzen et al., 2010). Numerous examples exist of successful enhancement efforts. “Wild” Pacific salmon fisheries have been augmented by hatcheries for decades. In the Philippines, hatchery-reared sea cucumbers (Holothuria scabra, Holothuriidae), sea urchins (Tripneustes gratilla, Toxopneustidae), and abalone (Haliotis asinina, Haliotidae) have all led to increased wild harvests (Juinio-Meñez, Bangi, Malay, & Pastor, 2008; Juinio-Meñez et al., 2013; Lebata-Ramos et al., 2013). Also in the Philippines, long-term efforts resulted in the successful restocking of giant clams (Tridacna gigas, Tridacninae) at more than 40 locations (Gomez & Mingoa-Licuanan, 2006). However, stock enhancement is often very expensive and results can be mixed and controversial (Bell, Leber, Blankenship, Loneragan, & Masuda, 2008). If handled improperly, stock enhancement has the potential to affect the genetic diversity, disease risk, and overall fitness of wild stocks (Jørstad et al., 2008; McGinnity et al., 1997) and typically needs to be done in conjunction with other management practices, including habitat restoration and fisheries regulations (Taylor et al., 2017).

### Escapes
Organisms that escape from mariculture farms can potentially compete directly for resources (e.g., food, space, mates) with wild counterparts and may affect genetic fitness (Naylor et al., 2005). Escapes occur from both small, more frequent “leakages”, and episodic large-scale events. Additionally, “escape through spawning” - when farmed species are able to spawn in an open production system like marine net-pens and release larval fish into the surrounding environment - has been documented for several species such as cod (Gadus morhua, Gadidae) and gilthead seabream (Sparus aurata, Sparidae) (Jørstad et al., 2008; S. Somarakis, Pavlidis, Saapoglou, Tsigenopoulos, & Dempster, 2013). 

The largest reason for escapes is technological failure (e.g. mooring failure, inappropriate cages, net damage from predators, etc.), followed by storm events and, to a lesser extent, human error (e.g. poor handling, damage by workboats, etc.) (Jackson et al., 2015; Jensen, Dempster, Thorstad, Uglem, & Fredheim, 2010; Thorvaldsen, Holmen, & Moe, 2015). While technological improvements and strong regulations can reduce the frequency of escapes, they rarely can be eliminated completely (Jensen et al., 2010). Escapes due to human error are addressable with better management, training, and oversight. The risks posed by escaped farmed fish should be thought of as a function of the probability of escape, the magnitude of the escape event, and the likely impacts of escaped fish on wild populations, ecosystems, and society. Understanding the risks associated with escapes is particularly relevant for management and policy as the scale and geographic scope of net-pen mariculture expands. To this end, the U.S. National Oceanic and Atmospheric Agency (NOAA) recently developed the Off-shore Mariculture Escapes Genetics Assessment (OMEGA) model to help decision makers better understand effects and design management strategies (Gruenthal, Jason, Blair, & Michael, 2017).

Although the occurrence and size of escape events are well documented, much less empirical evidence exists regarding the subsequent effects on the fitness of wild populations. Fisheries can play an active role in mitigating the genetic and competition risks posed by escaped farm fish. For example, artisanal fisheries were successful in recapturing over 60% of the biomass following a large escape event of gilthead seabream in the Mediterranean (Izquierdo-Gomez & Sanchez-Jerez, 2016). In such events, coordination between fisheries and mariculture management can reduce ecological impacts while providing economic windfalls to local fisheries. Similarly, fishers can serve as an early warning and monitoring system for escapes if farmed fish are sufficiently different from wild conspecifics such that they can be visually distinguished. Tags or fin clippings may also be used to ease identification of farmed individuals.

Escapes may exhibit life history characteristics (e.g., faster growth reflecting selective breeding) and behavioral differences (e.g., aggression) that stress wild con-specifics, potentially increasing their mortality (McGinnity et al., 1997; McGinnity et al., 2003; Naylor et al 2000; Einum & Fleming 1997). The degree (or presence) of negative impacts depends on the respective competitive abilities of cultured and wild species as well as their spatial and temporal overlap (Houde, Wilson & Neff, 2017). Escapes have been shown to be both competitively and reproductively inferior to wild conspecifics (Fleming et al., 2000). If interbreeding occurs between farmed and wild fish, genetic homogenization could result in a wild population that is less resilient to environmental pressures, particularly if the genetic makeup of farmed species is less diverse than that of the wild populations (Naylor et al., 2005; Fleming et al., 2000). Mariculture often employs selective breeding for advantageous traits like faster growth and disease resistance, and genetic drift can occur when mariculture operations stock wild juveniles that are a limited representation of the wild population (Hutchings & Fraser, 2008). Much of the research on genetic pollution from mariculture has focused on salmonids, with widespread genetic introgression and loss of fitness documented in wild populations in Norway, North America, and Ireland (Karlsson et al., 2016; McGinnity et al., 1997; Morris et al., 2008). However, spawning success of escaped individuals is generally lower than for wild fish and depends on numerous factors, complicating predictions for other taxa (Karlsson et al., 2016).

When farmed outside of their native range, escaped fish may establish feral populations and mariculture is considered a major avenue of exotic species introductions worldwide (Molnar, Gamboa, Revenga, & Spalding, 2008; Naylor et al., 2001), although invasion risk is highly variable. Some species, such as Atlantic salmon, are poor colonizers outside their native range while others, such as the Japanese oyster (Crassostrea gigas, Ostreidae), are widely established (Houde, Wilson & Neff, 2017; Arthur et al., 2010; Naylor et al., 2001). As we look to the future, climate change will make mariculture possible in regions where it currently does not exist, potentially increasing the risk of exotic species introductions (Holmer, 2010). Fortunately, promising new approaches, such as the use of environmental DNA, are improving our detection and understanding of invasive impacts (Clusa, Miralles, Basanta, Escot, & García-Vázquez, 2017).

Another important consideration is whether to allow the farming of genetically modified (GM) species. More than 35 species of fish have been genetically engineered, most commonly to enhance growth and feed efficiency (Devlin, Sundström, & Muir, 2006). Ecological and food safety concerns have kept GM fish out of commercial production. However, in 2015, the U.S. Food and Drug Administration approved the first GM fish (Atlantic salmon) for human consumption. Production must occur only in land-based facilities, as the potential ecological consequences on wild populations are not well understood (Devlin, Sundström, & Leggatt, 2015). Lab experiments have demonstrated hybridization between GM Atlantic salmon and wild brown trout (Salmo trutta, Salmonidae) (Oke, Westley, Moreau, & Fleming, 2013). Transgenic hybrids were viable, exhibited faster growth, and expressed competitive dominance over both transgenic and non-transgenic (wild) fish, suppressing growth by 82 and 54 percent, respectively. With commercial production of GM fish on the horizon there is a need for robust assessments of their potential ecological and economic benefits and risks.

One-way genetic modification can actually reduce risks to wild populations is through the use of triploid individuals (i.e., three sets of chromosomes). Triploidy can be easily induced in many commercial species, resulting in sterile individuals that have also been shown, in the case of shellfish, to exhibit superior growth (Piferrer et al., 2009). While triploidy appears promising for mitigating genetic and invasive risks, inducing triploidy is seldom 100% effective and escaped triploids will still compete directly with wild fish, warranting further investigation (Fjelldal, Wennevik, Fleming, Hansen, & Glover, 2014).

### Disease and parasite transmission
Marine diseases, although natural, have ecological consequences for fisheries and mariculture that cost billions of dollars each year and affect all major commercial species groups (Lafferty et al., 2015). Since diseases can move between wild and farmed populations and impose economic hardships on both sectors, effective disease management is mutually beneficial and requires cooperation and effective information sharing. Disease outbreak risk depends on wild host density and the intensity of mariculture production (Krkošek, 2009). Thus, fisheries and mariculture managers must collaborate to ensure that management plans account for both the density of farmed individuals (stocking density of individuals within a farm and the density of farms across the seascape) and the proximity and abundance of wild conspecifics.

Diseases and parasites often originate from wild populations, but mariculture poses elevated risks of disease and parasite transmission to wild stocks, both from increasing the frequency and mobility of pathogens in the environment and by potential reductions in immunity resulting from interbreeding (Johansen et al., 2011). Disease and parasite transmission from farmed to wild populations is well documented for numerous species, however, assessing population level effects is far more challenging and thus remains a considerable knowledge gap (Heuch et al., 2011; Johansen et al., 2011; Sweet & Bateman, 2015). Several studies on the effects of sea lice from mariculture farms on wild salmon have reached contradictory conclusions (Krkošek et al., 2011; Marty, Saksida, & Quinn, 2010). A meta-analysis of mariculture impacts on wild salmonids found a significant and negative effect (as measured by mean tonnage of harvested salmon), but did not account for fishing effort or important environmental factors, such as temperature (Ford & Myers, 2008) - factors we know impact productivity of wild species independent of aquaculture (Nicola, Elvira, Jonsson, Ayllón, & Almodóvar, 2018; Payne et al., 2016).

Mariculture’s heavy use of antibiotics for combatting disease, particularly by the shrimp and salmon sectors, is a long-standing concern (Cabello, 2006; Naylor et al., 2000). Indeed, mariculture can increase the presence of antibiotic resistance among fish pathogens (Le, Munekage, & Kato, 2005) and poses a legitimate risk to fish and human health (Cabello, 2006). Though antibiotic use is tightly restricted in Europe, North America, and Japan, this is not the case in much of the developing world (Topp et al., 2018). Vaccination follows a similar pattern and is now prominent for finfish mariculture, though traditional vaccines are not possible for invertebrates (Stentiford et al., 2017). Another significant threat mariculture poses to wild fisheries is the accidental introduction of non-native diseases and parasites when cultured animals are moved between regions. Prominent examples include the transfer of infectious agents from Pacific oysters (Crassostrea gigas, Ostreidae) in California to eastern oysters (Crassostrea virginica, Ostreidae) in Maine, and from Pacific oysters from Japan to the same species in the United States (Burreson, Stokes, & Friedman, 2000; Friedman & Perkins, 1994). While successful control of invasive marine species is possible (Culver & Kuris, 2000), it is rare and thus many places have strict regulations on moving farmed species between regions.

## Socioeconomic Interactions

### Spatial exclusion
One of the most contentious issues in mariculture development is direct competition, perceived and real, for ocean space with commercial and recreational fisheries (Sivas & Caldwell, 2008). Declines in available fishing grounds, navigational disturbances, variation in landings, and competition with fish farmers for catches have all been observed following the introduction of mariculture to an area (Aguilar-Manjarrez, Soto, & Brummett, n.d.; Akyol & Ertosluk, 2010; Sanchez-Jerez et al., 2016). Conversion to coastal shrimp and fish ponds can also privatize public lands formerly accessible to small-scale fishers and intertidal gleaners (Primavera, 2006). In Portugal, the degree to which mariculture affects available fishing area, navigation, and catch variability has been shown to influence the satisfaction of adjacent fishing communities (Ramos et al., 2015). Small-scale fisheries are often limited to nearshore coastal areas due to vessel size and power constraints. Spatial conflicts between these fisheries and mariculture will likely increase in the future as nearshore and coastal space becomes increasingly scarce. Industrial fisheries may also be impacted as mariculture moves offshore.

### Market competition
Products from wild fisheries and mariculture compete in the market, affecting farm-gate and ex-vessel prices as well as the demand for seafood products (Asche, Bjørndal, & Young, 2001). In theory, the introduction of mariculture could be both socially beneficial or detrimental in the long run depending on the degree of ecological interaction (Regnier & Schubert, 2016). Although a reasonable body of research has investigated the economic interactions between the two sectors, conclusions vary (Bjørndal & Guillen, 2016). At the global level, mariculture expansion has increased the overall demand for seafood and expanded the market for fishery products used for feeds (FAO, 2014; Naylor et al., 2009). The result is a higher total seafood supply with lower prices, reduced price volatility, and increased resilience (Asche, Dahl, & Steen, 2015; Dahl & Oglend, 2014; Jennings et al., 2016; Troell et al., 2014). However, at the individual fishery level, the effects of market competition depend on numerous factors, including the species and technologies involved, the degree of substitutability between products, the fishery management in place, and the presence of other interactions (spatial, ecological) outside of the market.

The evidence supporting market integration of farmed and wild fish is limited and largely dominated by studies of salmon markets. Farmed and wild salmon have been shown to be close substitutes on the market, often resulting in price decreases for all salmon species (Asche, Guttormsen, Sebulonsen, & Sissener, 2005). Similarly, an econometric analysis of landings of Spanish fresh fish found that mariculture production had a negative effect on the quantity of fish landings due to clear substitution between farmed and wild products (Castillo-Manzano, López-Valpuesta, Gonzalez-Laxe, & Pedregal, 2014). There is also clear evidence of a global market for shrimp, meaning shrimp fishers cannot mitigate losses due to supply shocks (natural disasters, oil spills, etc.) by raising prices (Asche, Bennear, Oglend, & Smith, 2012). Other studies show clear market differentiation. Bjørndal & Guillen (2017) found no market integration between farmed and wild gilthead seabream and European seabass (Dicentrarchus labrax, Moronidae), with price crises for farmed products not affecting wild products.

Consumer preferences play an important role in determining the degree to which similar products compete on the market. A recent study of consumer preferences in British Columbia, Canada found the distinction between farmed and wild seafood was the second most important factor to consumers, with the majority of respondents indicating a clear preference for wild fish (Murray, Wolff, & Patterson, 2017). Similarly, 80% of consumers in the EU seafood market were found to prefer wild fish, although country of origin and freshness were considerably more important factors relative to the obtaining method (farmed vs. wild) in consumers’ purchasing decisions (Claret et al., 2012).  However, price premiums for eco-labeled farmed salmon have been found to equal, and sometimes exceed, premiums for eco-labeled capture fishery products, suggesting environmental concern is the major issue segmenting the farmed and wild fish market (Ankamah-Yeboah, Nielsen, & Nielsen, 2016; Bronnmann & Asche, 2017).

## Aligning Fisheries and Mariculture Management
Interactions with mariculture occur at varying spatial scales and, in the absence of effective regulations, can have both positive and negative impacts on wild populations and their associated fisheries (Table 2). Additive effects could bring about long-term regional consequences for both sectors from disease, habitat and water quality degradation, reduced genetic fitness, overharvesting, invasive species, and price competition. On the other hand, mariculture practices have been used to enhance wild populations for decades, can improve local water quality, and shelter populations from fishing effort while expanding the market and overall demand for seafood products (Figure 2; Table 2). Just as the “race to fish” drives fishery overexploitation, a “rush to farm” can bring about an array of impacts for which producers are not held accountable (Subasinghe, Soto, & Jia, 2009). By examining when the decisions of mariculture farmers do not negatively affect their own production or the production of other farmers, we can better anticipate the issues where mariculture management is unlikely to address the concerns of capture fisheries. 

Fishery management approaches are designed to achieve one or more of the following goals: control fishing mortality, restore age-structure, protect marine habitat, and/or protect subpopulation structure to preserve genetic diversity (Selig et al., 2017). Overexploitation is likely to remain the primary concern for fisheries management, and the effects of overfishing could influence both the degree to which capture fisheries and mariculture overlap and/or conflict and the resilience of wild stocks to potential negative externalities of mariculture. Climate change can also exacerbate these issues (Pershing et al., 2015) and is expected to have profound effects on the distribution of commercially targeted species (Perry et al., 2005). Thus, it will be increasingly important for fisheries managers to consider how an expanding mariculture sector may affect target stocks and support or conflict with a ‘working waterfront’. While conflicts may emerge, the presence of aquaculture can also provide economic support for harbors and ports used by both industries, especially given seasonal variation of wild capture (e.g., Trombly et al., 2016). However, there is limited research around this socioeconomic interaction.

Mariculture management aims to limit a broad array of environmental impacts, primarily related to water quality (stocking density, feed use, chemical/antibiotics), disease risk, and invasive species because these are important economic issues, are often required by regulations, or negatively influence public perception of mariculture (Froehlich et al., 2017; Lafferty et al., 2015). In these cases, mariculture and fisheries are largely aligned - poor practices at the farm level can negatively impact all farms (internal) and capture fisheries (external) at the regional level (Table 2). Further integration of fisheries and aquaculture management could benefit from more advanced modeling efforts that incorporate both sectors in an ecosystem framework. Ecosystem-based models are commonly used in aquaculture modeling (Ferreira et al., 2007; Tsagaraki et al., 2011; Dowd, 2005), and could serve as a foundation for more holistic models that consider effects of the two sectors in concert.  

### Co-management strategies
The challenge for fisheries management is to deal with those impacts that are partially or entirely external to the individual fish farmer and therefore unlikely to be adequately addressed, if at all, by mariculture management alone. This presents an important opportunity for policy makers to figure out how to achieve cooperative management between the fisheries and mariculture sectors. Such an outcome lacks much precedent and requires adaptive management strategies that carefully balance precaution with empirics to support a sustainable and economically viable seafood industry. Eroding the distrust that often exists among mariculture and fishery stakeholders should be a key prerequisite (Martínez-Novo, Lizcano, Herrera-Racionero, & Miret-Pastor, 2017), and can be supported by approaches that ensure all stakeholders feel involved in the decision-making process and secure in their access to sustainable marine resources.

### Rights-based management
Conflicts in natural resource use arise when property rights are poorly defined, as assessed by the spatial, temporal, and quantitative “dimensions” of the property right (Ostrom, 2015; Yandle, 2007). In fisheries, property rights are primarily “withdrawal” rights, where fishers own the right to harvest the resource. In contrast, mariculture grants property rights in the form of “access” rights, the right to develop and control a farm in a defined physical property (Schlager & Ostrom, 1992). Thus, while property rights can be well-defined within a sector, fisheries and mariculture are generally granted rights to fundamentally different aspects of marine resources.

In some cases, rights-based fisheries management is spatial, such as Territorial Use Rights for Fisheries (TURFs), where fishers are granted ownership of the fish stock within a designated area. In these situations, the costs of unsustainable mariculture are internalized; poor farming practices by the community will negatively affect the fisheries for which they have exclusive rights. Similarly, TURFs provide the necessary incentives for investing in active resource management such as stock enhancement (Lorenzen et al., 2010). By aligning incentives, spatial rights-based approaches to resource management can allow communities to decide on appropriate levels and locations of both activities, not just fishing effort.

When property rights exist in capture fisheries, they can be used to facilitate arbitration. In New Zealand, if a proposed sustainable mariculture operation will adversely affect the harvest quota of fishers, an arbitrator must determine the economic value of the proposed mariculture venture relative to the fishery. If the proposed farming activities are found to be of “materially greater economic value” than the impact on fishers’ harvest quota, the project will be allowed to proceed and the quota owners will be compensated for the loss of value incurred (Office of the Minister for Primary Industries, 2012). The presence or absence of rights-based fishery management also influences how market competition from mariculture products will affect the fishery. For an unregulated open access fishery, theory suggests mariculture expansion will lower prices and lead to reduced fishing effort (Hoagland, Jin, & Kite-Powell, 2003). Such an outcome may allow overexploited fish stocks to recover but will be a financial hardship for the fishery (Anderson, 1985). Similar outcomes have been documented for limited-entry fisheries. Valderrama & Anderson (2010) found that growth in the salmon mariculture industry lowered prices for Bristol Bay Sockeye salmon (Oncorhynchus nerka, Salmonidae) to a level where participation in the fishery declined and fishing permits went unused. In regulated fisheries that lack property rights, fishing effort is usually constrained by biological considerations, neglecting the economic consequences for the profitability of the fishery when competing with farmed species (Natale et al., 2013). Fisheries managed with property rights, on the other hand, incentivize stewardship and are better equipped to increase efficiency, reduce costs, and buffer against falling prices (Valderrama & Anderson, 2010). For overexploited stocks, improved fisheries management can reduce both supply, and prices for mariculture suppress the sector’s overall growth potential in markets dominated by wild fish (F. Jensen, Nielsen, & Nielsen, 2014). Thus, the emergence of mariculture provides a strong rationale for rights-based approaches to managing fisheries facing competition from mariculture.

### Spatial Planning
When determining where to site mariculture farms, an important aspect is weighing the production potential and profitability of a given site(s) against the relative value of that site to wild fisheries that could be impacted (Gentry et al., 2017b). To this end, comprehensive marine spatial planning (MSP) has emerged as a means to achieve ecological, economic, and social objectives by analyzing and appropriately allocating different uses to marine spaces (Halpern, McLeod, Rosenberg, & Crowder, 2008) and illustrating tradeoffs to support decision-making. Importantly, mariculture is highly space efficient and an MSP analysis can often identify options for mariculture development that generate large yields at minimal cost to fishing yields from reduced fishing grounds (Lester et al., 2018). Designating allocated zones for aquaculture (AZAs), defined as ‘a marine area where the development of aquaculture has priority over other uses’, is a critical step in the MSP process and helps define the extent to which mariculture may encroach on traditional fishing grounds. The use of AZAs (or equivalent legislative and administrative tools) is already globally widespread and includes, among others, applications in Europe, New Zealand, Australia, Ecuador, and Chile (Sanchez-Jerez et al., 2016). However, AZAs alone do not prevent potential negative externalities from mariculture, which requires a subsequent site selection process that considers the specific issues and risks associated with different types of mariculture (Aguilar-Manjarrez, Soto, & Brummett, 2017). Furthermore, these zones can vary in their rules around fishing activities, potentially allowing fishing that is compatible with farming, and in their regulations regarding different types of aquaculture. Although there are no fundamental differences in the underlying spatial planning process for fed vs unfed mariculture, there are different impacts and spatial scales for stakeholders to consider for different species and farming methods. Integrated multi-trophic aquaculture (IMTA), in which fed and unfed mariculture are co-located, is one promising strategy for mitigating impacts from fed mariculture (Wartenberg et al., 2017; Troell et al., 2009), but large scale IMTA, as seen in China, can still pose serious environmental challenges (Liu & Su, 2017). Similarly, the co-location of mariculture with offshore wind farms has been proposed as a potential means to minimize the spatial impact of mariculture on traditional fishing grounds (Gimpel et al., 2015).

A key challenge to the MSP process is quantifying potential impacts from mariculture on capture fisheries, which is not straightforward and thus their inclusion in spatial planning models has largely been evaluated qualitatively (McKindsey, Thetmeyer, Landry, & Silvert, 2006). However, more quantitative approaches to the inclusion of mariculture in MSP process are emerging. Lester et al. (2018), developed an analytical MSP framework for guiding offshore mariculture (bivalve, finfish, and kelp) development in relation to other sectors (including wild-capture fisheries) and environmental concerns in California, USA. To further support such analyses, improved models of the potential interactions between mariculture and wild fisheries, as described in this paper, are necessary, particularly pertaining to FAD and MPA effects. For example, Xuan & Armstrong (2016) developed a bioeconomic model to examine when capture-based mariculture has a negative effect on wild fish stocks (e.g., lower intrinsic growth rate due to the stocking of wild juveniles). Their results suggest implementing an MPA of a certain size may result in better outcomes (e.g., wild catch, mariculture production, net present values) under both open access and optimal fisheries management. 
Time-area closures are a form of spatial management widely used in fisheries to prevent overfishing and minimize by-catch (Dunn, Boustany, & Halpin, 2011). These approaches tend to be effective at addressing their specific design objective but not necessarily other broad-scale objectives (Dichmont et al., 2013). Mariculture managers also employ time-area closures in the form of fallowing - where farm sites are emptied and not restocked for a period of time. This strategy helps to reduce disease risk and environmental impacts associated with nutrient loading. In some cases, it may be possible to synchronize these efforts and site mariculture in areas temporarily closed to fishing while simultaneously freeing up the space previously occupied by the farms. Such a strategy is likely best suited for invertebrates and demersal species with small geographic ranges, such as the Atlantic sea scallop (Placopecten magellanicus, Scallop) fisheries, where time-area closures are widely used. In Nova Scotia, Canada, CPUE for American lobsters (Homarus americanus, Lobster) decreased during fish farm operation and increased markedly during a three-year fallow period (Loucks, Smith, & Fisher, 2014). Thus, declines in CPUE could potentially be mitigated if fishing grounds can be rotated to align with the fallow periods in different areas. 

### Stock Enhancement
Stock enhancement science is progressing to where, in some cases, it is now possible to preemptively evaluate the potential success and impacts of stock enhancement efforts in conjunction with fisheries management decisions (Lorenzen et al., 2013). As the number of domesticated marine species developed for mariculture continues to rise, so too will the opportunities and economic feasibility of stock enhancement and restoration of wild populations thanks to improved understanding of species’ life cycles. However, genetic considerations differ between the two sectors; mariculture focuses on traits advantageous for growth and disease resistance while the genetic composition of individuals released for stock enhancement should reflect the wild population to the greatest extent possible. Reconciling these different objectives may make collaboration between hatchery managers and the mariculture sector challenging, especially where mariculture and fisheries are regulated by different government agencies. A promising example of a collaborative model for promoting both commercial culture and restoration is the U.S. National Shellfish Initiative.

In order to be successful, stock enhancement programs must be supported by adaptive fishery management that sets outcome-oriented goals, such as a net increase in landings, and updates management decisions accordingly (Lorenzen et al., 2010). Despite being a highly successful mariculture species, Chinese efforts to restock the large yellow croaker (Larimichthys crocea, Sciaenidae) failed due largely to poor management and continued overfishing pressure (Liu & De Mitcheson, 2008). Enhancement efforts must also be applied at the population scale; often making these strategies unsuitable for marine finfish outside of certain localized coastal populations (Kitada & Kishino, 2006). In contrast, many invertebrate species are particularly appealing for stock enhancement due to their high value, low feed requirements, and sedentary nature (Bell, Purcell, & Nash, 2008). The effectiveness of stock enhancement greatly depends on the release strategy (habitat, animal size at release, season, etc.) and recent evidence suggests coupling stock enhancement efforts with a network of marine reserves can improve outcomes by reducing mortality of released individuals (Dolorosa, Grant, & Gill, 2013).

Fisheries may employ mariculture techniques, beyond the use of hatcheries, which are more commonly associated with mariculture (Klinger et al., 2013). For example, the ratio of bait to total catch in the American lobster fishery often exceeds 2:1 due to the ability for small individuals to repeatedly feed on the bait and escape the traps, effectively representing a feed conversion ratio greater than most mariculture species (Harnish & Willison, 2009; Tacon & Metian, 2015). There is emerging recognition of the important contribution made by these “hybrid” production systems but better recognition in data reporting is crucial, as such practices directly affect fishery management and how we gauge sustainability (Klinger et al., 2013). Collectively, appropriately designed stock enhancement and well-leveraged hybrid production systems present an opportunity to improve conservation, economic, and food security outcomes for wild fisheries, while also helping to eliminate the perception of an inherent conflict between wild fisheries and mariculture.

Finally, for species threatened with extinction, mariculture may offer both ecological and economic paths to a solution. Restocking endangered marine species has been discussed for several decades and was used to successfully restore an endangered white sturgeon (Acipenser transmontanus, Sturgeon) population (Anders, 1998; Ireland, Anders, & Siple, 2002). “Supply-side” economic approaches can theoretically reduce the incentive to poach endangered species by flooding the market with farmed product (Damania & Bulte, 2007). The potential for mariculture to produce high volumes of endangered marine species, such as totoaba (Totoaba macdonaldi, Sciaenidae), at low cost make supply-side approaches promising relative to terrestrial species, for which the efficacy has been repeatedly questioned (Kirkpatrick & Emerton, 2010; Rueda-López, Lazo, Reyes, & Viana, 2011).

# Conclusion
Mariculture is currently operating well below its potential and its expansion has been hampered in part by concern and uncertainty around interactions with marine capture fisheries. In some cases, risks are relatively low: well-managed and carefully sited farms, particularly of low-density bivalves or algae, can prosper with minimal impacts to wild stocks. Potentially negative ecological and socioeconomic effects on wild fisheries do exist, however, but many of these effects can be reduced or eliminated with a combination of spatial planning and well-designed management strategies. Though disease transmission, genetic introgression, and the use of wild fish for feed and seed are concerns, the performance of mariculture is improving and public policies that establish property rights and guide planning are facilitating sustainable development of the sector in many countries. Where mariculture management is unlikely to address externalities on capture fisheries, management strategies like TURFs, MPAs, and time-area closures show promise. There are also potential synergistic benefits that mariculture can provide to wild stocks or fisheries in the form of protection from fishing, increased demand for seafood, and stock enhancement. Ongoing research is necessary, particularly regarding disease transmission and host-density thresholds; implications of the FAD and MPA effects on population dynamics; fitness effects of genetic introgression; impacts of capture-based mariculture; and the substitutability of wild and farmed products. Ultimately, providing for the projected increase in seafood demand will depend heavily on mariculture and understanding how best to manage, as well as leverage, the sector’s interactions with capture fisheries is critical.

# Acknowledgments 
TC, SEL, and RRG acknowledge financial support from the Waitt Foundation. HEF was funded by the Science for Nature and People Partnership (SNAPP) Open-Ocean Aquaculture Expert Working Group. The authors report no conflicts of interest. 
 
# References 

